sonar.projectKey=bt1234-sectiona-2026-calculator-amgoit
sonar.projectName=bt1234-sectiona-2026-calculator-amgoit
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml